version: 0.2

env:
  variables:
    EKS_CLUSTER_NAME: "my-eks-cluster"
    AWS_DEFAULT_REGION: "us-east-2"

phases:
  pre_build:
    commands:
      - echo "Setting up kubeconfig for EKS..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo "Fetching new image URI from build artifact..."
      - 'export IMAGE_URI=$(cat $CODEBUILD_SRC_DIR_BuildArtifact/imageDetail.json | jq -r .ImageURI)'
      - 'echo "Loaded image: $IMAGE_URI"'

  build:
    commands:
      - 'echo "Deploying image: $IMAGE_URI"'
      - envsubst < deployment.yaml > deployment-final.yaml
      - kubectl apply -f deployment-final.yaml --validate=false
      - kubectl apply -f service.yaml --validate=false
      - echo "Verifying rollout..."
      - kubectl rollout status deployment/mindtrack-deployment

  post_build:
    commands:
      - echo "Deployment successful."
